### PR TITLE
Port to serverless 0.5.*

### LINKED ISSUE #8: Version 0.0.7 does not work with serverless 0.5.1
The plug in version 0.0.7 does not seem to work with serverless 0.5.1

```
TypeError: Class extends value #<Serverless> is not a function or null
    at module.exports (/usr/src/app/voting-app/node_modules/serverless-plugin-sns/index.js:10:39)
    at Serverless._loadPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:286:25)
    at Serverless.loadProjectPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:240:10)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:77:41
From previous event:
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:73:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:17:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

### PR DESCRIPTION
**Pull request by moee**
This should fix #8 

Please note: Serverless introduced a new command to remove functions in 0.5.0 (`sls function remove`). This port does not support automatic removal of subscriptions.

### CODE REVIEW

**Comment by martinlindenberg** [comment]
sorry for the delay... didnt receive any messages from github about the issue :(

fix is merged

**Comment by martinlindenberg** [comment]
new release created and pushed to npm
