### ISSUE TITLE
Version 0.0.7 does not work with serverless 0.5.1

### ISSUE THREAD

**Issue by moee** [martinlindenberg/serverless-plugin-sns#8]
The plug in version 0.0.7 does not seem to work with serverless 0.5.1

```
TypeError: Class extends value #<Serverless> is not a function or null
    at module.exports (/usr/src/app/voting-app/node_modules/serverless-plugin-sns/index.js:10:39)
    at Serverless._loadPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:286:25)
    at Serverless.loadProjectPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:240:10)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:77:41
From previous event:
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:73:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:17:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by srg-clearlaunch** [comment]
+1

**Comment by martinlindenberg** [comment]
comments are in https://github.com/martinlindenberg/serverless-plugin-sns/pull/9
